module.exports = {
  "USER_ALREADY_EXISTS": "USER_ALREADY_EXISTS",
  "WRONG_LOGIN": "WRONG_LOGIN",
  "SESSION_EXPIRED": "SESSION_EXPIRED",
  "NO_ACCESS": "NO_ACCESS",
  "RESET_PASSWORD_TOKEN_EXPIRED": "RESET_PASSWORD_TOKEN_EXPIRED",
  "USER_NOT_ACTIVATED": "USER_NOT_ACTIVATED",
  "GENERAL_ERROR": "GENERAL_ERROR"
}